set title 'Bug Trend (by week) 07/03/2013 - 09/05/2013'
set boxwidth 0.3
set style fill solid 1.000000 border -1
set bmargin 5
set lmargin 5
set rmargin 5
set pointsize 2
set ylabel 'Count'
set tics scale 0.0
set grid y
set xtics rotate by -45
set term png size 800,600
set output 'static\843ce130-16b9-11e3-a5f2-00155ddef300.png'
set yrange [0:14]
set key autotitle columnhead
plot 'static\843ce130-16b9-11e3-a5f2-00155ddef300.data' using ($0-0.2):2 index 0 with boxes title '   sandy ', \
''                      using ($0+0.2):2 index 1 with boxes title ' Irene ', \
''                      using ($0):2 index 2 with boxes title 'Tao', \
''                      using ($0):2:xticlabels(int($0)% 1==0 ? strcol(1):'')  index 3 with linespoints lt 4 pt 7 title 'Average Time'
set output
