set title 'Bug Trend (by week) 08/01/2013 - 09/06/2013'
set boxwidth 0.3
set style fill solid 1.000000 border -1
set bmargin 5
set lmargin 5
set rmargin 5
set pointsize 2
set ylabel 'Count'
set tics scale 0.0
set grid y
set xtics rotate by -45
set term png size 800,600
set output 'static\9217f00f-16b9-11e3-b419-00155ddef300.png'
set yrange [0:246]
set key autotitle columnhead
plot 'static\9217f00f-16b9-11e3-b419-00155ddef300.data' using ($0-0.2):2 index 0 with boxes title '   Incoming Bugs', \
''                      using ($0+0.2):2 index 1 with boxes title '     Closed Bugs', \
''                      using ($0):2:xticlabels(int($0)% 1==0 ? strcol(1):'') index 2 with linespoints lt 4 pt 7 title 'Active Bugs'
set output
