//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceSync
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ResourceSync")]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="www.Intertech.com", ConfigurationName="IResource")]
public interface IResource
{
    
    [System.ServiceModel.OperationContractAttribute(Action="www.Intertech.com/IResource/GetResource", ReplyAction="www.Intertech.com/IResource/GetResourceResponse")]
    bool GetResource(string resourceID);
    
    [System.ServiceModel.OperationContractAttribute(Action="www.Intertech.com/IResource/ReleaseResource", ReplyAction="www.Intertech.com/IResource/ReleaseResourceResponse")]
    void ReleaseResource(string resourceID);
    
    [System.ServiceModel.OperationContractAttribute(Action="www.Intertech.com/IResource/ResetAllResource", ReplyAction="www.Intertech.com/IResource/ResetAllResourceResponse")]
    void ResetAllResource();
    
    [System.ServiceModel.OperationContractAttribute(Action="www.Intertech.com/IResource/Add", ReplyAction="www.Intertech.com/IResource/AddResponse")]
    int Add(int x, int y);
    
    [System.ServiceModel.OperationContractAttribute(Action="www.Intertech.com/IResource/GetData", ReplyAction="www.Intertech.com/IResource/GetDataResponse")]
    string GetData(int value);
    
    [System.ServiceModel.OperationContractAttribute(Action="www.Intertech.com/IResource/GetDataUsingDataContract", ReplyAction="www.Intertech.com/IResource/GetDataUsingDataContractResponse")]
    ResourceSync.CompositeType GetDataUsingDataContract(ResourceSync.CompositeType composite);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IResourceChannel : IResource, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ResourceClient : System.ServiceModel.ClientBase<IResource>, IResource
{
    
    public ResourceClient()
    {
    }
    
    public ResourceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ResourceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ResourceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ResourceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool GetResource(string resourceID)
    {
        return base.Channel.GetResource(resourceID);
    }
    
    public void ReleaseResource(string resourceID)
    {
        base.Channel.ReleaseResource(resourceID);
    }
    
    public void ResetAllResource()
    {
        base.Channel.ResetAllResource();
    }
    
    public int Add(int x, int y)
    {
        return base.Channel.Add(x, y);
    }
    
    public string GetData(int value)
    {
        return base.Channel.GetData(value);
    }
    
    public ResourceSync.CompositeType GetDataUsingDataContract(ResourceSync.CompositeType composite)
    {
        return base.Channel.GetDataUsingDataContract(composite);
    }
}
